---
- hosts: localhost
  collections:
    - netapp.storagegrid

  vars:
    - grid_admin_base_url: "{{ grid_url }}"

  tasks:
    - include: tasks/get_tenantid_from_bucket.yaml
    - include: tasks/get_tenant_users.yaml
    - include: tasks/get_user_keys.yaml
